version: '3.8'

services:

  monopatin_mysql_db:
    image: mysql:latest
    container_name: monopatin_mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "pleaseDontHackMe!123"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - ./monopatin_mysql_data:/var/lib/mysql
    restart: always

  monopatin_mongo_db:
    image: mongo:4.4.18
    container_name: monopatin_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pleaseDontHackMe!123
    ports:
      - "27018:27017"
    volumes:
      - ./monopatin_mongo_data:/data/db
    restart: always

