services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: integrador1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql